apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteMany
  nfs:          
    server: storage.k8s.local
    path: "/mnt/sharedfolder"
